spring:
  application:
    name: ticketmanagement

  datasource:
    url: jdbc:postgresql://localhost:5432/ticketingdb
    username: postgres
    password: postgres


  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        hbm2ddl:
          auto: create

server:
  port: 8080
